name: Check Approved Label

on:
  pull_request:
    types:
      - opened
      - synchronize
      - labeled
      - unlabeled
      - reopened

jobs:
  approved:
    runs-on: ubuntu-latest

    steps:
      - name: Check for Approved label
        if: contains(github.event.pull_request.labels.*.name, 'Approved')
        run: echo "PR has the Approved label."

      - name: Approved label is missing
        if: "!contains(github.event.pull_request.labels.*.name, 'Approved')"
        run: |
          echo "PR does not have the Approved label."
          exit 1
